In [1]:
import numpy as np
import scipy as sp
import math as m
from prettytable import PrettyTable
import library_assignment_2 as lib


Question 1

In [2]:
#Define A and B

A=4*np.eye(6)
A= A+np.diagflat([-1,-1,0,-1,-1],1)+np.diagflat([-1,-1,0,-1,-1],-1)+np.diagflat([-1,-1,-1],3)+np.diagflat([-1,-1,-1],-3)
A= A.tolist()
B = np.array([[2],[1],[2],[2],[1],[2]]).tolist()

#check if they are symmetric
q1_flag = lib.symcheck(A)
if q1_flag == True:
    print("A is symmetric")
else:
    raise ValueError("A is not symmetric")

A is symmetric


In [3]:

#Cholesky Decomposition

A1 = np.copy(A).tolist()    
B1 = np.copy(B).tolist()   
chol_ans = lib.Cholesky_solve(A1,B)


#Gauss Seidel

tolerence_q1 = 1e-6
GS_ans,steps = lib.gauss_seidel(A,B,tolerence_q1) 


#print the results
p=PrettyTable()
p.field_names = ["Variable", "Cholesky", "Gauss Seidel"]

for i in range(len(chol_ans)):
    p.add_row([f"x_{i+1}","{:.6f}".format(chol_ans[i][0]),"{:.7f}".format(GS_ans[i][0])])
print(p)
print("Number of iterations for Gauss Seidel Method : ",steps)


+----------+----------+--------------+
| Variable | Cholesky | Gauss Seidel |
+----------+----------+--------------+
|   x_1    | 1.000000 |  0.9999998   |
|   x_2    | 1.000000 |  0.9999998   |
|   x_3    | 1.000000 |  0.9999999   |
|   x_4    | 1.000000 |  0.9999999   |
|   x_5    | 1.000000 |  0.9999999   |
|   x_6    | 1.000000 |  0.9999999   |
+----------+----------+--------------+
Number of iterations for Gauss Seidel Method :  16


Question 2

In [4]:
#define the matrices

A=[
    [0,4,2,0,1],
    [4,0,4,10,1],
    [2,5,1,3,13],
    [11,3,0,1,2],
    [3,2,7,1,0]
]
B=[[20],[15],[92],[51],[15]]
print("Diagonally dominant metrix check: ",lib.diagonal_dom_check(A))
A_new=lib.make_DD(A,B)
#Solving using the Gauss-Jordan Method

GJ_ans = lib.gauss_jordan_solve(np.copy(A).tolist(),np.copy(B).tolist())

#LU Decomposition

LU_ans = lib.LU_solve(np.copy(A).tolist(),np.copy(B).tolist())

p=PrettyTable()
p.field_names = ["Variable", "Gauss Jordan", "LU Decomposition"]
for i in range(len(GJ_ans)):
    p.add_row([f"x_{i+1}","{:.4f}".format(GJ_ans[i][0]),"{:.4f}".format(LU_ans[i][0])])
   
print(p)


Diagonally dominant metrix check:  False
+----------+--------------+------------------+
| Variable | Gauss Jordan | LU Decomposition |
+----------+--------------+------------------+
|   x_1    |    2.6746    |      2.6746      |
|   x_2    |    3.7119    |      3.7119      |
|   x_3    |   -0.0533    |     -0.0533      |
|   x_4    |   -0.0744    |     -0.0744      |
|   x_5    |    5.2591    |      5.2591      |
+----------+--------------+------------------+


Question 3

In [5]:
import numpy as np
A = [
    [2,-3,0,0,0,0],
    [-1,4,-1,0,-1,0],
    [0,-1,4,0,0,-1],   
    [0,0,0,2,-3,0],
    [0,-1,0,-1,4,-1],
    [0,0,-1,0,-1,4]
    ]

B = [
    [-5/3],
    [2/3],
    [3],
    [-4/3],
    [-1/3],
    [5/3]
    ]

A1 = np.copy(A)

A = ((np.array(A)+np.array(A).T)/2).tolist()  

y_s,step = lib.conjugate_gradient_solve(A,B,[[0],[0],[0],[0],[0],[0]],1e-4)
print(np.array(y_s))
print("The Number of Iterations for Conjugate Gradient Method is: ",step)


print(np.matmul(A1,y_s))


[[-1.5       ]
 [-0.66666667]
 [ 0.66666667]
 [-1.66666667]
 [-1.        ]
 [ 0.33333333]]
The Number of Iterations for Conjugate Gradient Method is:  6
[[-1.        ]
 [-0.83333333]
 [ 3.        ]
 [-0.33333333]
 [-2.        ]
 [ 1.66666667]]


In [6]:
def conjugate_gradient(A,b,x,tol=0.000001,itermax=54):
  r=b-A@x
  d=r
  i=0
  residue=np.sqrt(r@r)
  while i<=itermax and residue >= tol:
    alpha=(r@r)/(d@(A@d))
    x=x+alpha*d
    r1=r-alpha*(A@d)
    beta=(r1@r1)/(r@r)
    d=r1+beta*d
    r=r1
    residue=np.sqrt(r@r)
    i+=1
  return x
def conjugate_gradient_inverse(A):
  l=[]
  I=np.identity(A.shape[1])
  x0=0.5*np.ones(A.shape[1])
  for j in range(A.shape[1]):
    x=conjugate_gradient(A,I[:,j],x0)
    l.append(x)
  result=np.vstack(l)
  return result.T
M=np.array([[2,-3,0,0,0,0],[-1,4,-1,0,-1,0],[0,-1,4,0,0,-1],[0,0,0,2,-3,0],[0,-1,0,-1,4,-1],[0,0,-1,0,-1,4]])
b=np.array([-(5/3),(2/3),3,(-4/3),(-1/3),(5/3)])
x0=np.ones(6)

In [7]:
print(conjugate_gradient(M,b,x0))

[-0.3447479   0.32688228  0.99761917 -0.68164938 -0.00712292  0.66452815]


In [8]:
Q=conjugate_gradient_inverse(M)
print(Q)

[[0.91297646 0.93578768 0.25615252 0.21230963 0.50834423 0.16956203]
 [0.28746764 0.59692854 0.17256342 0.13813613 0.3030059  0.11216624]
 [0.08350403 0.15499575 0.31979197 0.04920808 0.10121089 0.10776105]
 [0.21230963 0.50834423 0.16956203 0.91297646 0.93578768 0.25615252]
 [0.13813613 0.3030059  0.11216624 0.28746764 0.59692854 0.17256342]
 [0.04920808 0.10121089 0.10776105 0.08350403 0.15499575 0.31979197]]


Question 4